/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.63
 * Generated at: 2015-09-20 01:53:47 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.jsp.back;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class back_005findex_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\r\n");
      out.write("<title>Gc微博后台</title>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("\r\n");
      out.write("<!-- Bootstrap -->\r\n");
      out.write("<link href=\"css/bootstrap.min.css\" rel=\"stylesheet\" media=\"screen\">\r\n");
      out.write("<link href=\"css/bootstrap-theme.min.css\" rel=\"stylesheet\" media=\"screen\">\r\n");
      out.write("\r\n");
      out.write("<!-- Bootstrap Admin Theme -->\r\n");
      out.write("<link href=\"css/bootstrap-admin-theme.css\" rel=\"stylesheet\"\r\n");
      out.write("\tmedia=\"screen\">\r\n");
      out.write("\r\n");
      out.write("<!-- Vendors -->\r\n");
      out.write("<link href=\"vendors/easypiechart/jquery.easy-pie-chart.css\"\r\n");
      out.write("\trel=\"stylesheet\" media=\"screen\">\r\n");
      out.write("<link href=\"vendors/easypiechart/jquery.easy-pie-chart_custom.css\"\r\n");
      out.write("\trel=\"stylesheet\" media=\"screen\">\r\n");
      out.write("\r\n");
      out.write("<!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->\r\n");
      out.write("<!--[if lt IE 9]>\r\n");
      out.write("        <script type=\"text/javascript\" src=\"js/html5shiv.js\"></script>\r\n");
      out.write("        <script type=\"text/javascript\" src=\"js/respond.min.js\"></script>\r\n");
      out.write("    <![endif]-->\r\n");
      out.write("</head>\r\n");
      out.write("<body class=\"bootstrap-admin-with-small-navbar\">\r\n");
      out.write("\t<nav class=\"navbar navbar-default navbar-inverse navbar-fixed-top \"\r\n");
      out.write("\t\trole=\"navigation\">\r\n");
      out.write("\t<div class=\"container\">\r\n");
      out.write("\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t<!-- Brand and toggle get grouped for better mobile display -->\r\n");
      out.write("\t\t\t<div class=\"navbar-header\">\r\n");
      out.write("\t\t\t\t<button type=\"button\" class=\"navbar-toggle\" data-toggle=\"collapse\"\r\n");
      out.write("\t\t\t\t\tdata-target=\"#bs-example-navbar-collapse-1\">\r\n");
      out.write("\t\t\t\t\t<span class=\"sr-only\">Toggle navigation</span> <span\r\n");
      out.write("\t\t\t\t\t\tclass=\"icon-bar\"></span> <span class=\"icon-bar\"></span> <span\r\n");
      out.write("\t\t\t\t\t\tclass=\"icon-bar\"></span>\r\n");
      out.write("\t\t\t\t</button>\r\n");
      out.write("\t\t\t\t<a class=\"navbar-brand\" href=\"#\">Gc微博后台</a>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<!-- Collect the nav links, forms, and other content for toggling -->\r\n");
      out.write("\t\t\t<div class=\"collapse navbar-collapse\"\r\n");
      out.write("\t\t\t\tid=\"bs-example-navbar-collapse-1\">\r\n");
      out.write("\t\t\t\t<ul class=\"nav navbar-nav\">\r\n");
      out.write("\t\t\t\t\t<li class=\"active\"><a href=\"#\">首页</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"back_help.jsp\">使用介绍</a></li>\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t<form class=\"navbar-form navbar-left\" role=\"search\">\r\n");
      out.write("\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t<input type=\"text\" class=\"form-control\" placeholder=\"请输入内容\">\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<button type=\"submit\" class=\"btn btn-default\">搜索</button>\r\n");
      out.write("\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t<ul class=\"nav navbar-nav navbar-right\">\r\n");
      out.write("\t\t\t\t\t<li class=\"dropdown\"><a href=\"#\" class=\"dropdown-toggle\"\r\n");
      out.write("\t\t\t\t\t\tdata-toggle=\"dropdown\">管理员<b class=\"caret\"></b></a>\r\n");
      out.write("\t\t\t\t\t\t<ul class=\"dropdown-menu\">\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"../nav/index.jsp\">退出登录</a></li>\r\n");
      out.write("\t\t\t\t\t\t</ul></li>\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<!-- /.navbar-collapse -->\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t</nav>\r\n");
      out.write("\r\n");
      out.write("\t<div class=\"container\">\r\n");
      out.write("\t\t<!-- left, vertical navbar & content -->\r\n");
      out.write("\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t<!-- left, vertical navbar -->\r\n");
      out.write("\t\t\t<div class=\"col-md-2 bootstrap-admin-col-left\">\r\n");
      out.write("\t\t\t\t<ul class=\"nav navbar-collapse collapse bootstrap-admin-navbar-side\">\r\n");
      out.write("\t\t\t\t\t<li class=\"active\"><a href=\"back_index.jsp\"><i\r\n");
      out.write("\t\t\t\t\t\t\tclass=\"glyphicon glyphicon-chevron-right\"></i> 首页</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"back_about.jsp\"><i\r\n");
      out.write("\t\t\t\t\t\t\tclass=\"glyphicon glyphicon-chevron-right\"></i> 关于我们</a></li>\r\n");
      out.write("\t\t\t\t\t<li class=\"disabled\"><a href=\"#\"><i\r\n");
      out.write("\t\t\t\t\t\t\tclass=\"glyphicon glyphicon-chevron-right\"></i> 日历</a>\r\n");
      out.write("\t\t\t\t\t<!-- calendar.html --></li>\r\n");
      out.write("\t\t\t\t\t<li class=\"disabled\"><a href=\"#\"><i\r\n");
      out.write("\t\t\t\t\t\t\tclass=\"glyphicon glyphicon-chevron-right\"></i> 统计图表</a>\r\n");
      out.write("\t\t\t\t\t<!-- stats.html --></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"back_journal_release.jsp\"><i\r\n");
      out.write("\t\t\t\t\t\t\tclass=\"glyphicon glyphicon-chevron-right\"></i> 日志发布</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"back_journal_admin.jsp\"><i\r\n");
      out.write("\t\t\t\t\t\t\tclass=\"glyphicon glyphicon-chevron-right\"></i> 日志管理</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"back_users.jsp\"><i\r\n");
      out.write("\t\t\t\t\t\t\tclass=\"glyphicon glyphicon-chevron-right\"></i> 用户管理</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"back_message.jsp\"><i\r\n");
      out.write("\t\t\t\t\t\t\tclass=\"glyphicon glyphicon-chevron-right\"></i> 留言管理</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"back_image.jsp\"><i\r\n");
      out.write("\t\t\t\t\t\t\tclass=\"glyphicon glyphicon-chevron-right\"></i> 图片管理</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"back_admin_information.jsp\"><i\r\n");
      out.write("\t\t\t\t\t\t\tclass=\"glyphicon glyphicon-chevron-right\"></i> 账户中心</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"#\"><i\r\n");
      out.write("\t\t\t\t\t\t\tclass=\"glyphicon glyphicon-chevron-right\"></i> 留白1</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"#\"><i\r\n");
      out.write("\t\t\t\t\t\t\tclass=\"glyphicon glyphicon-chevron-right\"></i> 留白2</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"#\"><i\r\n");
      out.write("\t\t\t\t\t\t\tclass=\"glyphicon glyphicon-chevron-right\"></i> 留白3</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"#\"><i\r\n");
      out.write("\t\t\t\t\t\t\tclass=\"glyphicon glyphicon-chevron-right\"></i> 留白4</a></li>\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<!-- content -->\r\n");
      out.write("\t\t\t<div class=\"col-md-10\">\r\n");
      out.write("\t\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t\t<div class=\"alert alert-success bootstrap-admin-alert\">\r\n");
      out.write("\t\t\t\t\t\t<button type=\"button\" class=\"close\" data-dismiss=\"alert\">×</button>\r\n");
      out.write("\t\t\t\t\t\t<h4>Successful visit of Backstage:&nbsp&nbsp&nbsp&nbsp\r\n");
      out.write("\t\t\t\t\t\t\t2015年9月9日 15:21</h4>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t\t<div class=\"panel panel-default bootstrap-admin-no-table-panel\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"panel-heading\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"text-muted bootstrap-admin-box-title\">统计</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"pull-right\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<span class=\"badge\"></span>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div\r\n");
      out.write("\t\t\t\t\t\t\tclass=\"bootstrap-admin-panel-content bootstrap-admin-no-table-panel-content collapse in\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"col-md-3\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"easyPieChart\" data-percent=\"73\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tstyle=\"width: 110px; height: 110px; line-height: 110px;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t73%\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<canvas width=\"110\" height=\"110\"></canvas>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"chart-bottom-heading\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<span class=\"label label-info\">访问量</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"col-md-3\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"easyPieChart\" data-percent=\"53\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tstyle=\"width: 110px; height: 110px; line-height: 110px;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t53%\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<canvas width=\"110\" height=\"110\"></canvas>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"chart-bottom-heading\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<span class=\"label label-info\">注册量</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"col-md-3\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"easyPieChart\" data-percent=\"83\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tstyle=\"width: 110px; height: 110px; line-height: 110px;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t83%\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<canvas width=\"110\" height=\"110\"></canvas>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"chart-bottom-heading\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<span class=\"label label-info\">日志量</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"col-md-3\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"easyPieChart\" data-percent=\"13\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tstyle=\"width: 110px; height: 110px; line-height: 110px;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t13%\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<canvas width=\"110\" height=\"110\"></canvas>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"chart-bottom-heading\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<span class=\"label label-info\">留言量</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t\t<div class=\"panel panel-default\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"panel-heading\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"text-muted bootstrap-admin-box-title\">相册</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"pull-right\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<span class=\"badge\">1,462</span>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t<hr>\r\n");
      out.write("\t\t\t<footer role=\"contentinfo\">\r\n");
      out.write("\t\t\t<p>\r\n");
      out.write("\t\t\t\t&copy; 2015 <a href=\"#\" target=\"_blank\">Gc</a>\r\n");
      out.write("\t\t\t</p>\r\n");
      out.write("\t\t\t</footer>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\t<!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->\r\n");
      out.write("\t<script type=\"text/javascript\"\r\n");
      out.write("\t\tsrc=\"http://code.jquery.com/jquery-2.0.3.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\t<!-- Include all compiled plugins (below), or include individual files as needed -->\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"js/bootstrap.min.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\"\r\n");
      out.write("\t\tsrc=\"js/twitter-bootstrap-hover-dropdown.min.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\"\r\n");
      out.write("\t\tsrc=\"vendors/easypiechart/jquery.easy-pie-chart.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\t<script type=\"text/javascript\">\r\n");
      out.write("\t\t$(function() {\r\n");
      out.write("\t\t\t// Easy pie charts\r\n");
      out.write("\t\t\t$('.easyPieChart').easyPieChart({\r\n");
      out.write("\t\t\t\tanimate : 1000\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t});\r\n");
      out.write("\t</script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
