/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.63
 * Generated at: 2015-10-10 15:55:50 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.jsp.nav;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import dao.ReplyDao;
import other.Tool;
import dao.JournalDao;
import empty.Journal;
import java.util.ArrayList;
import empty.User;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			"../error.jsp", true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("  <meta charset=\"UTF-8\">\r\n");
      out.write("  <link href=\"css/news.css\" rel=\"stylesheet\">\r\n");
      out.write("  <link href=\"css/nav.css\" rel=\"stylesheet\">\r\n");
      out.write("  <title>GC的博客</title>\r\n");
      out.write("  <style type=\"text/css\">\r\n");
      out.write("        body {\r\n");
      out.write("          background-color:#edecec;\r\n");
      out.write("          background-image: url('img/1.jpg');\r\n");
      out.write("          background-position: center;\r\n");
      out.write("          background-repeat:repeat;\r\n");
      out.write("          background-attachment: fixed;\r\n");
      out.write("          background-size: 100%,auto;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("  </style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<!--导航开始-->\r\n");
      out.write("\t<!-- java start -->\r\n");
      out.write("\t");

		//获取Session user
		session = request.getSession();
		User user = null;
		if(session.getAttribute("user") != null){
			user = (User)session.getValue("user");
		}
		/*
		 *获取服务器返回的是否登出成功的信息ds
		 */
		 String ds = "";
		if(request.getParameter("ds")!=null){
			ds = request.getParameter("ds");
		}
	
      out.write("\r\n");
      out.write("\t<!-- java end -->\r\n");
      out.write("  <div id=\"nav\">\r\n");
      out.write("    <ul class=\"nav-menu clearfix unstyled\">\r\n");
      out.write("      <li><a href=\"#\" class=\"three-d active\">\r\n");
      out.write("        主页\r\n");
      out.write("        <span class=\"three-d-box\"><span class=\"front\">主页</span><span class=\"back\">主页</span></span>\r\n");
      out.write("      </a></li>\r\n");
      out.write("      <li><a href=\"../Journal/Journal.jsp\" class=\"three-d\">\r\n");
      out.write("        日志\r\n");
      out.write("        <span class=\"three-d-box\"><span class=\"front\">日志</span><span class=\"back\">日志</span></span>\r\n");
      out.write("      </a></li>\r\n");
      out.write("      <li><a href=\"#\" class=\"three-d\">\r\n");
      out.write("        TA\r\n");
      out.write("        <span class=\"three-d-box\"><span class=\"front\">TA</span><span class=\"back\">TA</span></span>\r\n");
      out.write("      </a></li>\r\n");
      out.write("      <li><a href=\"../information/information.jsp\" class=\"three-d\">\r\n");
      out.write("        博主\r\n");
      out.write("        <span class=\"three-d-box\"><span class=\"front\">博主</span><span class=\"back\">博主</span></span>\r\n");
      out.write("      </a></li>\r\n");
      out.write("      <li><a href=\"#\" class=\"three-d\">\r\n");
      out.write("        空间\r\n");
      out.write("        <span class=\"three-d-box\"><span class=\"front\">空间</span><span class=\"back\">空间</span></span>\r\n");
      out.write("      </a></li>\r\n");
      out.write("      <li><a href=\"../editor/messagebox.jsp\" class=\"three-d\">\r\n");
      out.write("        留言板\r\n");
      out.write("        <span class=\"three-d-box\"><span class=\"front\">留言板</span><span class=\"back\">留言板</span></span>\r\n");
      out.write("      </a></li>\r\n");
      out.write("      <li><a href=\"../back/back_login.jsp\" class=\"three-d\">\r\n");
      out.write("        后台\r\n");
      out.write("        <span class=\"three-d-box\"><span class=\"front\">后台</span><span class=\"back\">后台</span></span>\r\n");
      out.write("      </a></li>\r\n");
      out.write("      ");

      	if(user == null){
      
      out.write("\r\n");
      out.write("      <li><a href=\"#\" class=\"three-d\">\r\n");
      out.write("        登陆/注册\r\n");
      out.write("        <span class=\"three-d-box\"><span class=\"front\">登陆/注册</span><span class=\"back\">登陆/注册</span></span></a>\r\n");
      out.write("        <ul class=\"clearfix unstyled drop-menu\">\r\n");
      out.write("          <li><a href=\"../login/login.jsp\" class=\"three-d\">\r\n");
      out.write("              登陆\r\n");
      out.write("              <span class=\"three-d-box\"><span class=\"front\">登陆</span><span class=\"back\">登陆</span></span>\r\n");
      out.write("          </a></li>\r\n");
      out.write("          <li><a href=\"../registered/registered.jsp\" class=\"three-d\">\r\n");
      out.write("            注册\r\n");
      out.write("            <span class=\"three-d-box\"><span class=\"front\">注册</span><span class=\"back\">注册</span></span>\r\n");
      out.write("          </a></li>\r\n");
      out.write("        </ul>\r\n");
      out.write("      </li>\r\n");
      out.write("      ");
}else{ 
      out.write("\r\n");
      out.write("      <li><a href=\"#\" class=\"three-d\">\r\n");
      out.write("        登陆成功/登出\r\n");
      out.write("        <span class=\"three-d-box\"><span class=\"front\">登陆成功/登出</span><span class=\"back\">");
      out.print(user.getUser_nick());
      out.write("</span></span></a>\r\n");
      out.write("        <ul class=\"clearfix unstyled drop-menu\">\r\n");
      out.write("          <li><a href=\"/myblog/SessionDo\" class=\"three-d\">\r\n");
      out.write("            登出\r\n");
      out.write("            <span class=\"three-d-box\"><span class=\"front\">登出</span><span class=\"back\">登出</span></span>\r\n");
      out.write("          </a></li>\r\n");
      out.write("        </ul>\r\n");
      out.write("      </li>\r\n");
      out.write("      ");
} 
      out.write("\r\n");
      out.write("    </ul>\r\n");
      out.write("  </div>\r\n");
      out.write("<!--导航结束-->\r\n");
      out.write("<!--最新更新start--> \r\n");
      out.write("\t<!-- java start -->\r\n");
      out.write("\t");

		ArrayList<Journal> list = null;
		list = JournalDao.SelectTopJournal5();
	
      out.write("\r\n");
      out.write("\t<!-- java end -->\r\n");
      out.write("  <div class=\"center_show\">\r\n");
      out.write("    <div class=\"topnews\">\r\n");
      out.write("        <h1>^_^&nbsp&nbsp<b>文章</b>推荐&nbsp&nbsp^_^</h1>\r\n");
      out.write("        ");

        	for(Journal journal:list){
        
      out.write("\r\n");
      out.write("        <div class=\"blogs\">\r\n");
      out.write("          <figure><img style='width:180px; height:180px;' src=\"../../image/journalheader/");
      out.print(journal.getImgpath());
      out.write("\"></figure>\r\n");
      out.write("          <ul>\r\n");
      out.write("            <h3><a href=\"../Journal/journal_each.jsp?id=");
      out.print(journal.getJournal_id());
      out.write('"');
      out.write('>');
      out.print(journal.getTitle());
      out.write("</a></h3>\r\n");
      out.write("            <div class=\"journal_summary\">\r\n");
      out.write("            \t<p>");
      out.print(journal.getSummary());
      out.write("</p>\r\n");
      out.write("            </div>\r\n");
      out.write("            <p class=\"autor\"><span class=\"lm f_l\"><a href=\"../Journal/Journal.jsp?cfy=");
      out.print(journal.getClassify());
      out.write('"');
      out.write('>');
      out.print(Tool.ClassifyNumToClassify(journal.getClassify()));
      out.write("</a></span><span class=\"dtime f_l\">");
      out.print(Tool.changDateTile(journal.getDatetime()));
      out.write("</span><span class=\"viewnum f_r\">浏览（<a href=\"#\">很多</a>）</span><span class=\"pingl f_r\">评论（<a href=\"#\">");
      out.print(ReplyDao.countReplyByArticleID(journal.getJournal_id()));
      out.write("</a>）</span></p>\r\n");
      out.write("          </ul>\r\n");
      out.write("        </div>\r\n");
      out.write("         ");

        	}
        
      out.write("\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("<!--最新更新end-->\r\n");
      out.write("<!--留白start-->\r\n");
      out.write("  <div class=\"blank\">Designed and built with all the love in the world by <a href=\"#\">@GC</a></div>\r\n");
      out.write("  <div class=\"blank-bottom\">用爱创造世界</div>\r\n");
      out.write("<!--留白end-->\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
      out.write("  <script type=\"text/javascript\">\r\n");
      out.write("\tvar ds = \"\";\r\n");
      out.write("\tds = ");
      out.print(ds);
      out.write(";\r\n");
      out.write("\tif(ds == 1){\r\n");
      out.write("\t\talert(\"登出成功，跳转到微博主页\");\r\n");
      out.write("\t}\r\n");
      out.write("  </script>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
